name: Security-Compliance-Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  analyze-security:
    name: Run CodeQL Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'javascript' # Cambia según tu código

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Upload SARIF report
        uses: actions/upload-artifact@v4
        with:
          name: codeql-report
          path: ./codeql-results
