name: Security-Compliance-Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  security-checks:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Inicializar CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'autodetect'

      # 3. Ejecutar análisis CodeQL
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      # 4. Generar SBOM con Syft
      - name: Generate SBOM
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh
          ./syft dir:. -o json > sbom.json

      # 5. Crear carpeta para artefactos
      - name: Prepare artifacts
        run: |
          mkdir artifacts
          cp sbom.json artifacts/
          cp -r codeql-results artifacts/ || echo "CodeQL results not found"

      # 6. Comprimir artefactos en ZIP
      - name: Compress artifacts
        run: zip -r security-artifacts.zip artifacts

      # 7. Subir artefactos
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-artifacts
          path: security-artifacts.zip
